version: "3.8"
services:
  codefm-pre:
    container_name: codefm-pre
    build:
      context: .
      dockerfile: Dockerfile
    image: mfarrapeira/codefm-pre:latest
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=pre
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      app_name: codefm-pre
      prometheus_job: 'codefm-pre'
      prometheus_target: 'codefm.synology.me:8081'
    volumes:
      - ./logs:/app/logs
    networks:
      - logging
      - infisical_external
      - keycloak


networks:
  logging:
    external: true
  infisical_external:
    external: true
  keycloak:
    external: true
  sonarqube:
    external: true