services:
  codefm:
    container_name: codefm
    build:
      context: .
      dockerfile: Dockerfile
    image: mfarrapeira/codefm:latest
    ports:
      - "8081:8080"
    environment:
      - profile=prod
      - INFISICAL_TOKEN=st.378ff8e3-fc74-44a2-9867-3c27af45736c.d276c6a534321848e88fff5743c4036e.dafd369933b4f999dc6cd48105e3c87e
      - INFISICAL_API_URL=http://infisical-server:8080
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      app_name: codefm
      prometheus_job: 'codefm'
      prometheus_target: 'codefm.synology.me:8081'
    volumes:
      - ./logs:/app/logs
    networks:
      - logging
      - infisical_external
      - keycloak


networks:
  logging:
    external: true
  infisical_external:
    external: true
  keycloak:
    external: true
  sonarqube:
    external: true
