version: "3.8"
services:
  codefm:
    container_name: codefm
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: mfarrapeira/codefm:latest
    ports:
      - "8081:8080"
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      app_name: codefm
      prometheus_job: 'codefm'
      prometheus_target: 'codefm.synology.me:8081'
    volumes:
      - ./logs:/app/logs
      - ./data/student-photos:/app/data/student-photos
      - ./data/exercise-documents:/app/data/exercise-documents
      - ./data/exercise-student-document:/app/data/exercise-student-document
    networks:
      - logging
      - infisical_external
      - keycloak
      - kafka-network
      - redis-network


networks:
  logging:
    external: true
  infisical_external:
    external: true
  keycloak:
    external: true
  sonarqube:
    external: true
  kafka-network:
    external: true
  redis-network:
    external: true


