spring:
  datasource:
    codefm:
      url: jdbc:p6spy:mariadb://192.168.18.10:3306/codefm_pre
      username: codefm
    teachernotebook:
      url: jdbc:p6spy:mariadb://192.168.18.10:3306/teacher_notebook_pre
      username: codefm
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://codefm.synology.me:8480/realms/codefm-pre
  cache:
    redis:
      key-prefix: "codefm-pre::"


kafka:
  topic:
    user: codefm.pre.user