server:
  port: 8081

logging:
  config: classpath:logback-default.xml

spring:
  datasource:
    codefm:
      url: jdbc:p6spy:mariadb://192.168.18.10:3306/codefm_pre
      username: codefm
    teachernotebook:
      url: jdbc:p6spy:mariadb://192.168.18.10:3306/teacher_notebook_pre
      username: codefm
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://codefm.synology.me:8480/realms/codefm-pre
  kafka:
    bootstrap-servers: 192.168.18.10:9092
    consumer:
      properties:
        schema.registry.url: http://192.168.18.10:8082
    producer:
      properties:
        schema.registry.url: http://192.168.18.10:8082
    properties:
      schema.registry.url: http://192.168.18.10:8082

kafka:
  topic:
    user: codefm.local.user
  schema:
    registry:
      url: http://192.168.18.10:8082