name: Version Check

on:
  pull_request:
    branches:
      - master

permissions:
  pull-requests: write

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          path: master
          persist-credentials: false
          fetch-depth: 0

      - name: Checkout source branch (PR head)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: source
          persist-credentials: false
          fetch-depth: 0

      - name: Get version from master
        id: master_version
        run: |
          cd master
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get version from source branch
        id: source_version
        run: |
          cd source
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Compare versions
        id: compare_versions
        run: |
          MASTER_VERSION="${{ steps.master_version.outputs.version }}"
          SOURCE_VERSION="${{ steps.source_version.outputs.version }}"
          echo "Master version: $MASTER_VERSION"
          echo "Source version: $SOURCE_VERSION"
          if [[ "$SOURCE_VERSION" == *-SNAPSHOT ]]; then
            echo "ERROR: The version in the source branch (**$SOURCE_VERSION**) must NOT be a SNAPSHOT. Please set a release version before merging."
            exit 1
          fi
          if [ "$(printf '%s\n%s' "$MASTER_VERSION" "$SOURCE_VERSION" | sort -V | head -n1)" = "$SOURCE_VERSION" ]; then
            echo "ERROR: The version in the source branch (**$SOURCE_VERSION**) must be greater than the version in master (**$MASTER_VERSION**). Please increase the version before merging."
            exit 1
          fi

      - name: Comment on PR if version is not valid
        if: failure()
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :warning: The version in the source branch (**${{ steps.source_version.outputs.version }}**) must be **greater** than the version in `master` (**${{ steps.master_version.outputs.version }}**) **and must NOT be a SNAPSHOT**. Please set a release version before merging.
