name: Block Merge if Version is Not Increased

on:
  pull_request:
    branches:
      - master

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          path: master

      - name: Checkout develop (PR head)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: develop

      - name: Get version from master
        id: master_version
        run: |
          cd master
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get version from develop (PR)
        id: develop_version
        run: |
          cd ../develop
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Compare versions
        id: compare_versions
        run: |
          MASTER_VERSION="${{ steps.master_version.outputs.version }}"
          DEVELOP_VERSION="${{ steps.develop_version.outputs.version }}"
          echo "Master version: $MASTER_VERSION"
          echo "Develop version: $DEVELOP_VERSION"
          if [ "$(printf '%s\n%s' "$MASTER_VERSION" "$DEVELOP_VERSION" | sort -V | head -n1)" = "$DEVELOP_VERSION" ]; then
            echo "ERROR: The version in develop (**$DEVELOP_VERSION**) must be greater than the version in master (**$MASTER_VERSION**). Please increase the version before merging."
            exit 1
          fi

      - name: Comment on PR if version is not greater
        if: failure()
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :warning: The version in `develop` (**${{ steps.develop_version.outputs.version }}**) must be greater than the version in `master` (**${{ steps.master_version.outputs.version }}**). Please increase the version before merging.