name: Deploy PRE to Synology

permissions:
  pull-requests: write

on:
  issue_comment:
    types: [ created ]

jobs:
  deploy-pre:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, 'deploy-pre')
    runs-on: ubuntu-latest
    steps:
      - name: Get PR branch
        id: pr_branch
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          BRANCH=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $PR_URL | jq -r .head.ref)
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr_branch.outputs.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push PRE image
        run: |
          docker compose -f docker-compose-pre.yml build
          docker push ${{ secrets.DOCKERHUB_USER }}/codefm-pre:latest
        env:
          INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}

      - name: Create .env file
        run: echo "INFISICAL_TOKEN=${{ secrets.INFISICAL_TOKEN }}" > .env

      - name: Copy docker-compose-pre.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SYNOLOGY_HOST }}
          username: ${{ secrets.SYNOLOGY_USER }}
          password: ${{ secrets.SYNOLOGY_PASS }}
          source: "docker-compose-pre.yml"
          target: "~/codefm-pre"

      - name: Copy .env
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SYNOLOGY_HOST }}
          username: ${{ secrets.SYNOLOGY_USER }}
          password: ${{ secrets.SYNOLOGY_PASS }}
          source: ".env"
          target: "~/codefm-pre"

      - name: Create logs folder on Synology
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SYNOLOGY_HOST }}
          username: ${{ secrets.SYNOLOGY_USER }}
          password: ${{ secrets.SYNOLOGY_PASS }}
          script: mkdir -p ~/codefm-pre/logs

      - name: Deploy PRE via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SYNOLOGY_HOST }}
          username: ${{ secrets.SYNOLOGY_USER }}
          password: ${{ secrets.SYNOLOGY_PASS }}
          port: 22
          script: |
            export PATH=$PATH:/usr/local/bin
            cd ~/codefm-pre
            echo "Desplegando con perfil PRE"
            echo "${{ secrets.SYNOLOGY_PASS }}" | sudo -S /usr/local/bin/docker-compose -f docker-compose-pre.yml pull
            echo "${{ secrets.SYNOLOGY_PASS }}" | sudo -S /usr/local/bin/docker-compose -f docker-compose-pre.yml up -d
            echo "Variables de entorno:"
            cat .env

      - name: Clean up PRE images and containers
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SYNOLOGY_HOST }}
          username: ${{ secrets.SYNOLOGY_USER }}
          password: ${{ secrets.SYNOLOGY_PASS }}
          port: 22
          script: |
            docker ps -a --filter "name=^/codefm-pre$" -q | xargs -r docker rm -f
            docker images "${{ secrets.DOCKERHUB_USER }}/codefm-pre" --format "{{.Repository}}:{{.Tag}}" | grep -v ":latest" | xargs -r docker rmi -f

      - name: Comment on PR if deployment was successful
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: "✅ Deployment PRE completed successfully."
            });