name: Deploy to Synology Container Manager

permissions:
  pull-requests: write
  issues: write

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Validate trigger
        run: |
          if [[ "${{ github.event_name }}" == "issues" ]]; then
            [[ "${{ github.event.issue.title }}" == deploy* ]] || exit 1
          else
            [[ "${{ github.event.comment.body }}" == deploy* ]] || exit 1
          fi

      - name: Get PR branch if triggered by issue_comment
        id: pr_branch
        if: github.event_name == 'issue_comment'
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          if [[ -n "$PR_URL" ]]; then
            BRANCH=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $PR_URL | jq -r .head.ref)
            echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          fi

      - name: Extract ref to deploy (branch or tag)
        id: ref
        run: |
          if [[ "${{ github.event_name }}" == "issues" ]]; then
            CMD="${{ github.event.issue.title }}"
            ARGS=($CMD)
          elif [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            CMD="${{ github.event.comment.body }}"
            ARGS=($CMD)
          else
            echo "Trigger no soportado"
            exit 1
          fi
          
          if [[ "${ARGS[0]}" == "deploy" ]]; then
            if [[ ${#ARGS[@]} -eq 2 ]]; then
              REF="${ARGS[1]}"
              PROFILE="default"
              TYPE="branch"
            elif [[ ${#ARGS[@]} -eq 3 && "${ARGS[1]}" == "tag" ]]; then
              REF="${ARGS[2]}"
              PROFILE="default"
              TYPE="tag"
            else
              echo "Uso: deploy <rama> o deploy tag <nombre-tag>"
              exit 1
            fi
          elif [[ "${ARGS[0]}" == "deploy-pre" ]]; then
            if [[ ${#ARGS[@]} -eq 1 ]]; then
              if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
                PR_URL="${{ github.event.issue.pull_request.url }}"
                if [[ -n "$PR_URL" ]]; then
                  if [[ -n "${{ steps.pr_branch.outputs.branch }}" ]]; then
                    REF="${{ steps.pr_branch.outputs.branch }}"
                  elif [[ -n "${{ github.head_ref }}" ]]; then
                    REF="${{ github.head_ref }}"
                  else
                    echo "No se pudo determinar la rama del PR"
                    exit 1
                  fi
                  PROFILE="pre"
                  TYPE="branch"
                else
                  echo "deploy-pre solo se puede usar en comentarios de PR"
                  exit 1
                fi
              else
                echo "deploy-pre solo se puede usar en comentarios de PR"
                exit 1
              fi
            else
              echo "deploy-pre no admite parámetros"
              exit 1
            fi
          else
            echo "Comando no soportado"
            exit 1
          fi
          
          echo "ref=$REF" >> $GITHUB_OUTPUT
          echo "profile=$PROFILE" >> $GITHUB_OUTPUT
          echo "type=$TYPE" >> $GITHUB_OUTPUT
          echo "Perfil seleccionado: $PROFILE"

      - name: Checkout indicated ref (branch or tag)
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.ref.outputs.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image to Docker Hub
        run: |
          if [[ "${{ steps.ref.outputs.profile }}" == "pre" ]]; then
            docker compose -f docker-compose-pre.yml build
            docker push ${{ secrets.DOCKERHUB_USER }}/codefm-pre:latest
          else
            docker compose build
            docker push ${{ secrets.DOCKERHUB_USER }}/codefm:latest
          fi
        env:
          INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}

      - name: Create .env file
        run: echo "INFISICAL_TOKEN=${{ secrets.INFISICAL_TOKEN }}" > .env

      - name: Copy docker-compose.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SYNOLOGY_HOST }}
          username: ${{ secrets.SYNOLOGY_USER }}
          password: ${{ secrets.SYNOLOGY_PASS }}
          source: ${{ steps.ref.outputs.profile == 'pre' && 'docker-compose-pre.yml' || 'docker-compose.yml' }}
          target: "~/codefm"

      - name: Copy .env
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SYNOLOGY_HOST }}
          username: ${{ secrets.SYNOLOGY_USER }}
          password: ${{ secrets.SYNOLOGY_PASS }}
          source: ".env"
          target: "~/codefm"

      - name: Create logs folder on Synology
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SYNOLOGY_HOST }}
          username: ${{ secrets.SYNOLOGY_USER }}
          password: ${{ secrets.SYNOLOGY_PASS }}
          script: mkdir -p ~/codefm/logs

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SYNOLOGY_HOST }}
          username: ${{ secrets.SYNOLOGY_USER }}
          password: ${{ secrets.SYNOLOGY_PASS }}
          port: 22
          script: |
            export PATH=$PATH:/usr/local/bin
            cd ~/codefm
            if [ "${{ steps.ref.outputs.profile }}" = "pre" ]; then
              echo "Desplegando con perfil PRE"
              echo "${{ secrets.SYNOLOGY_PASS }}" | sudo -S /usr/local/bin/docker-compose -f docker-compose-pre.yml pull
              echo "${{ secrets.SYNOLOGY_PASS }}" | sudo -S /usr/local/bin/docker-compose -f docker-compose-pre.yml up -d
              echo "Variables de entorno:"
              cat .env
            else
              echo "Desplegando con perfil DEFAULT"
              echo "${{ secrets.SYNOLOGY_PASS }}" | sudo -S /usr/local/bin/docker-compose -f docker-compose.yml pull
              echo "${{ secrets.SYNOLOGY_PASS }}" | sudo -S /usr/local/bin/docker-compose -f docker-compose.yml up -d
              echo "Variables de entorno:"
              cat .env
            fi

      - name: Clean up unused images and containers on Synology
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SYNOLOGY_HOST }}
          username: ${{ secrets.SYNOLOGY_USER }}
          password: ${{ secrets.SYNOLOGY_PASS }}
          port: 22
          script: |
            if [ "${{ steps.ref.outputs.profile }}" = "pre" ]; then
              # Solo elimina el contenedor codefm-pre
              docker ps -a --filter "name=^/codefm-pre$" -q | xargs -r docker rm -f
              docker images "${{ secrets.DOCKERHUB_USER }}/codefm-pre" --format "{{.Repository}}:{{.Tag}}" | grep -v ":latest" | xargs -r docker rmi -f
            else
              # Solo elimina el contenedor codefm
              docker ps -a --filter "name=^/codefm$" -q | xargs -r docker rm -f
              docker images "${{ secrets.DOCKERHUB_USER }}/codefm" --format "{{.Repository}}:{{.Tag}}" | grep -v ":latest" | xargs -r docker rmi -f
            fi

      - name: Comment on PR or issue if deployment was successful
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const eventName = process.env.GITHUB_EVENT_NAME;
            let number;
            if (eventName === "issues") {
              number = context.payload.issue.number;
            } else if (eventName === "issue_comment") {
              number = context.payload.issue.number;
            } else {
              return;
            }
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
              body: "✅ Deployment completed successfully."
            });