name: Deploy to Synology Container Manager

on:
  issues:
    types: [opened]

jobs:
  deploy:
    if: github.event.issue.title == 'deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Synology Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SYNOLOGY_REGISTRY }}
          username: ${{ secrets.SYNOLOGY_USER }}
          password: ${{ secrets.SYNOLOGY_PASS }}

      - name: Build and push image with Compose
        run: |
          docker compose build
          docker tag codefm:latest ${{ secrets.SYNOLOGY_REGISTRY }}/codefm:latest
          docker push ${{ secrets.SYNOLOGY_REGISTRY }}/codefm:latest

      - name: Deploy on Synology via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SYNOLOGY_HOST }}
          username: ${{ secrets.SYNOLOGY_USER }}
          password: ${{ secrets.SYNOLOGY_PASS }}
          script: |
            docker pull ${{ secrets.SYNOLOGY_REGISTRY }}/codefm:latest
            docker compose down || true
            docker compose up -d
