name: Detect Secrets

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main, develop, feature/** ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks to detect secrets
        id: gitleaks
        run: |
          gitleaks detect --source . --report-format sarif --report-path gitleaks.sarif || true

      - name: Comment Gitleaks result on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('gitleaks.sarif', 'utf8');
            const body = report.length > 10000 ? 'The report is too large to display.' : `\`\`\`json\n${report}\n\`\`\``;
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🔒 **Gitleaks scan result:**\n${body}`
            });