name: Detect Secrets

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@v3.76.3
        with:
          scanArguments: --path . --fail