name: Detect Secrets

on:
  push:
    branches: [ main, develop, feature/** ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks to detect secrets
        uses: gitleaks/gitleaks-action@v2