name: Detect Secrets

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: files
        uses: tj-actions/changed-files@v44

      - name: Run Gitleaks on changed files
        if: steps.files.outputs.all_changed_files != ''
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-git --redact --exit-code=1 --verbose --source ${{ steps.files.outputs.all_changed_files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
