name: Detect Secrets

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks to detect secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --no-git -v