name: Detect Secrets

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: files
        uses: tj-actions/changed-files@v44

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o /usr/local/bin/gitleaks
          chmod +x /usr/local/bin/gitleaks

      - name: Run Gitleaks on changed files (current content only)
        if: steps.files.outputs.all_changed_files != ''
        run: |
          for file in ${{ steps.files.outputs.all_changed_files }}; do
            gitleaks detect --no-git --redact --exit-code=1 --verbose --source "$file"
          done