name: Detect Secrets

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Get list of changed files
        id: changed_files
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff --name-only origin/${{ github.base_ref }}...HEAD > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

      - name: Run Gitleaks on each changed file
        run: |
          echo "Scanning changed files with Gitleaks..."
          exit_code=0
          while read file; do
            if [ -f "$file" ]; then
              echo "Scanning $file"
              gitleaks detect --no-git --source="$file" --redact --verbose || exit_code=$?
            else
              echo "Skipping $file (not a regular file)"
            fi
          done < changed_files.txt
          exit $exit_code
