name: Detect Secrets

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks to detect secrets
        id: gitleaks
        run: |
          gitleaks detect --no-git -v \
            --report-format json \
            --report-path gitleaks-report.json || echo "Gitleaks found issues."

      - name: Parse Gitleaks results
        id: parse
        run: |
          if [ -s gitleaks-report.json ]; then
            echo "found_secrets=true" >> $GITHUB_OUTPUT
            echo "SECRETS=$(jq -r '.[] | "- Rule: \(.Rule) in \(.File): line \(.StartLine)"' gitleaks-report.json | head -n 20)" >> $GITHUB_ENV
          else
            echo "found_secrets=false" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR if secrets are found
        if: github.event_name == 'pull_request' && steps.parse.outputs.found_secrets == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const findings = process.env.SECRETS;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🔐 **Potential secrets detected in this pull request:**\n\n${findings}\n\nPlease review and remove any sensitive information before merging.`
            })
