name: Detect Secrets with Gitleaks

on:
  push:
    branches:
      - '**'           # Esto cubre todos los branches
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  gitleaks-scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gitleaks
        id: gitleaks
        run: |
          gitleaks detect --source . --report-format sarif --report-path gitleaks.sarif || true

      - name: Parse Gitleaks report
        id: parse
        run: |
          if [ -s gitleaks-report.json ]; then
            echo "found_secrets=true" >> $GITHUB_OUTPUT
            echo "SECRETS=$(jq -r '.[] | "- Rule: \(.Rule) in \(.File): line \(.StartLine)"' gitleaks-report.json)" >> $GITHUB_ENV
          else
            echo "found_secrets=false" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR with findings
        if: steps.parse.outputs.found_secrets == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const findings = process.env.SECRETS.split('\n').slice(0, 20).join('\n');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🔐 **Potential secrets detected in this pull request:**\n\n${findings}\n\nPlease review and remove any sensitive data before merging.`
            })
